[context.production.environment]
  HUGO_VERSION = "0.69.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.69.2"

[build]
publish = "public"
command = "hugo --theme=tranquilpeak --buildDrafts --gc --minify"